<p>Torna-se mais evidente a cada dia a contribuição positiva do mercado de capitais e, especificamente, o destacado papel do mercado acionário para o desenvolvimento econômico. <br><br>
A ideia de que o mercado acionário, notadamente nos países em desenvolvimento, envolveria apenas negociações na esfera financeira, desprovidas de qualquer impacto sobre o setor real da economia, mostrou-se definitivamente superada.
De acordo com estudos divulgados pelo Banco Mundial, foi encontrado um alto grau de correlação entre os indicadores dos mercados acionários e o crescimento médio verificado no período 1976-96. <br><br>
A conclusão foi de que o mercado acionário não apenas seguiu o crescimento econômico, mas proporcionou os meios para prognosticar as taxas futuras de crescimento do capital, da produtividade e da renda per capita. <br><br>
São inúmeras as contribuições a serem citadas: <br><br>
·         Ao carregar recursos dos poupadores e disponibilizá-los para o uso dos investidores, o mercado de ações incentiva não apenas a formação da poupança interna, mas, particularmente, a geração de poupança de longo prazo. É inegável a relação entre a formação de poupança com os processos de crescimento autossustentado e manutenção do desenvolvimento econômico. <br><br>
·         O mercado de ações, ao premiar, via maximização dos retornos, o uso eficiente dos recursos e o momento correto da tomada de decisão, torna o próprio mercado cada vez mais eficiente e esse efeito é transmitido aos demais setores da economia. Por sua vez, um mercado eficiente proporciona uma ampla gama de alternativas de financiamento, isoladamente ou pela combinação entre as diversas opções, reduzindo custos financeiros, o que contribui decisivamente para a saúde financeira das empresas, com consequente valorização do capital investido pelos acionistas. <br><br>
·         Um mercado acionário desenvolvido, com bom volume, liquidez e adequada regulamentação, facilita os negócios de mudança de controle/propriedade e privatização, o que tem contribuído para o aumento da produtividade econômica nos últimos anos, em nível global. <br><br>
·         A demanda por informações e demonstrações financeiras de qualidade, por parte do mercado acionário, é um fator que estimula a cultura empresarial e do público geral, com frutos para toda a atividade econômica. <br><br>
·         O mercado acionário reflete a opinião dos principais agentes sobre a conjuntura econômica doméstica e internacional e suas perspectivas, constituindo-se também em importante formador de opinião. Assim, os diagnósticos e recomendações originadas desse mercado são elementos que os condutores da política econômica costumam considerar na tomada de decisões. <br><br>
·         Finalmente, cabe destacar o papel fundamental de um mercado de ações eficiente e desenvolvido para atrair, maximizar e consolidar a presença e permanência do capital externo.
</p>
<p>
<strong>DIVERSIFIQUE OS INVESTIMENTOS</strong><br>
 <br>
Diversificação de investimentos é o termo técnico utilizado para designar a antiga recomendação de que "não se deve colocar todos os ovos na mesma cesta".<br>
Assim, da totalidade de seus recursos, o investidor deve separar o montante que estará comprometido com gastos de curto prazo e com pagamentos em datas fixas (mais os imprevistos) e destiná-lo a aplicações financeiras de curto prazo ou até mesmo mantê-lo em disponibilidade imediata.<br>
Da parcela destinada ao investimento de médio e longo prazos, poderá destinar parte a aplicações de renda fixa e parte a operações de renda variável (ou seja, uma aplicação cujo rendimento não se conhece com antecedência).<br>
Em princípio, quanto mais conservador, maior a parcela dedicada aos investimentos de renda fixa. Quanto mais agressivo, maior a exposição aos mercados de renda variável. Entretanto, a moderna gestão de fundos e carteiras consegue diminuir as diferenças de relação risco-retorno desses dois tipos de investimento por meio do uso de derivativos.<br>
Derivativos são instrumentos financeiros sofisticados, cujo valor se baseia em outro ativo, os quais propiciam a montagem de estratégias de proteção ("hedge") ou, ao contrário, de alavancagem.<br>
Entre as alternativas de investimento em renda variável destaca-se o investimento em ações. Quando este é realizado com expectativa de retorno de médio/longo prazos, o risco fica menor. Dessa forma, o risco passa a estar condicionado ao desempenho/resultado (lucro ou prejuízo) da companhia dentro de um horizonte temporal mais amplo.<br>
</p>