<p>Ações são títulos nominativos negociáveis que representam, para quem as possui, uma fração do capital social de uma empresa. Ação é um pedacinho de uma empresa.
Com um ou mais pedacinhos da empresa, você se torna sócio dela.</p>
<p>Quais são os tipos de ação?<br>
As ações podem ser:</p>
<p>·         <strong>ordinárias</strong>, que concedem àqueles que as possuem o poder de voto nas assembléias deliberativas da companhia; ou <br>
·         <strong>preferenciais</strong>, que oferecem preferência na distribuição de resultados ou no reembolso do capital em caso de liquidação da companhia, não concedendo o direito de voto, ou restringindo-o.</p>
<p>As ações, ordinárias ou preferenciais, são sempre nominativas, originando-se do fato a notação ON ou PN depois do nome da empresa.</p>
<p>As ações também podem ser diferenciadas por classes: A, B, C ou alguma outra letra que apareça após o "ON" ou o "PN". As características de cada classe são estabelecidas pela empresa emissora da ação, em seu estatuto social. Essas diferenças variam de empresa para empresa, portanto, não é possível fazer uma definição geral das classes de ações.</p>
<p><strong>O que são dividendos?</strong><br>
Uma empresa deve dividir os lucros com seus acionistas. Essa parcela direcionada aos detentores de ações é conhecida como dividendo. Ou seja, os dividendos correspondem à parcela de lucro distribuída aos acionistas, na proporção da quantidade de ações detida, apurado ao fim de cada exercício social. O estatuto social de uma companhia pode estabelecer o dividendo mínimo a ser distribuído, desde que não seja inferior a 25% de seu lucro líquido ajustado. Caso não haja previsão no estatuto social, o dividendo obrigatório deve corresponder, no mínimo, à metade do lucro líquido ajustado.
Quando uma empresa vai bem, ela divide os lucros com quem tem suas ações. <br>
Isso são dividendos.</p>
<p><strong>E bonificações?</strong><br>
As bonificações correspondem à distribuição de novas ações para os atuais acionistas. Excepcionalmente pode ocorrer a distribuição de bonificação em dinheiro. <br></p>
<p><strong>Como funcionam as subscrições de novas ações?</strong><br>
Os acionistas têm ainda preferência na compra de novas ações emitidas ou direito de preferência na subscrição. Além de garantir a possibilidade de manter a mesma participação no capital total, esse direito pode significar ganho adicional, dependendo das condições do lançamento. Por fim, se não exercido, o direito pode ser vendido a terceiros.</p>
<p><strong>OPÇÕES</strong></p>
<p><strong>Mercado de opções</strong> é o <a href="http://pt.wikipedia.org/wiki/Mercado" target="_blank">mercado</a> onde se negociam <strong>opções</strong>, que são instrumentos financeiros utilizados no <a href="http://pt.wikipedia.org/wiki/Mercado_financeiro" target="_blank">mercado financeiro</a>. Uma opção confere, ao titular, o direito (e não obrigação) de comprar ou de vender um determinado <a href="http://pt.wikipedia.org/wiki/Ativo" target="_blank">ativo</a> (<a href="http://pt.wikipedia.org/wiki/A%C3%A7%C3%A3o" target="_blank">ação</a>, <a href="http://pt.wikipedia.org/wiki/T%C3%ADtulo" target="_blank">título</a> ou <a href="http://pt.wikipedia.org/wiki/Bem" target="_blank">bem</a> qualquer) por um valor determinado.<u></u><u></u></p>
<p>Uma opção pode ser vista como uma apólice de seguro; em particular a opção de venda é análoga a um seguro de automóvel, pois permite recuperar um valor predeterminado pelo ativo, mesmo que este tenha desvalorizado muito. Já a opção de compra é semelhante ao sinal pago na compra de um imóvel, pois garante o preço fixo e a preferência na compra.<u></u><u></u></p>
<p>Uma opção, como o próprio nome diz, é de exercício opcional, ela só dá direitos a seu possuidor. O emissor ou lançador de opções, por outro lado, assume a obrigação de honrar o prometido pelo papel. Por conta disso, uma opção tem custo adicional, pago pelo possuidor.<u></u><u></u></p>
<p>A opção é bastante diferente de um contrato de futuros onde ambos os lados assumem certas obrigações e o preço do contrato é apenas a diferença entre o preço contratado do preço atual de mercado do objeto do contrato (soja, milho, petróleo ou outra commodity). Uma opção será sempre mais cara que um contrato de futuro semelhante, pois o lançador precisa ser remunerado pelo risco adicional.<u></u><u></u></p>
<p>As opções são instrumentos financeiros <a href="http://pt.wikipedia.org/wiki/Derivativo" target="_blank">derivativos</a>. Isto significa que o <a href="http://pt.wikipedia.org/wiki/Valor" target="_blank">valor</a> de uma opção e suas características de negociação estão ligadas a um ativo adjacente. Por exemplo, uma <em>opção da PETROBRAS PN</em> está ligada ao direito de compra ou venda do ativo <em>PETROBRAS PN (PETR4)</em>.<u></u><u></u></p>
<p>O ativo ao qual a opção está sendo negociada pode ser um ação, um índice, um contrato futuro, uma letra do tesouro, uma commodity, etc.<u></u><u></u></p>
<p>Embora seja um instrumento de controle de risco e <a href="http://pt.wikipedia.org/wiki/Hedge" target="_blank">hedge</a> o investimento em opções exige perfeita compreensão dos fundamentos e planejamento estratégico sob pena de graves prejuízos.<u></u><u></u></p>
<p>O <a href="http://pt.wikipedia.org/wiki/Investidor" target="_blank">investidor</a> que conhecer os fundamentos das opções, terá um meio efetivo de lidar com o risco pois passará a ter a sua disposição uma grande variedade de escolhas diferentes de investimentos.</p>
